apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: myapp-service
    type: flask-app
spec:
  type: LoadBalancer
  ports:  
  - targetPort: 8000
    port: 80
  selector:
    type: flask-app




